# Generated by Django 2.0.6 on 2018-06-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('gender', models.CharField(default='m', max_length=2)),
                ('meaning', models.CharField(max_length=191)),
                ('religion', models.CharField(default='h', max_length=2)),
            ],
        ),
    ]
