# Generated by Django 2.0.6 on 2018-06-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nameguru', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='meaning',
            field=models.CharField(default=None, max_length=191),
        ),
    ]
